### ISSUE TITLE
CVE-2019-12760 - Bad PoC

### ISSUE THREAD

**Issue by dhondta** [trickest/cve#23]
**Record** : [cve/2019/CVE-2019-12760.md](https://github.com/trickest/cve/blob/main/2019/CVE-2019-12760.md)

The PoC is the first mentioned reference : https://gist.github.com/dhondta/f71ae7e5c4234f8edfd2f12503a5dcc7
But the PoC found is : https://github.com/kaashmonee/rM2FS

The *PoC* found only *mentions* the vulnerability but is actually NOT the proof-of-concept. Note that the actual PoC (the first reference) has the keywords "*Proof-of-Concept*" mentioned in the Gist's description.

**Comment by dhondta** [comment]
Can someone fix the workflow ?...

**Comment by mhmdiaa** [comment]
Hi @dhondta,

Thanks for the heads up! I've gone ahead and [added that invalid PoC to the blacklist](https://github.com/trickest/cve/commit/3a7cf1bc0d88d01612e85d0a33e8e17399b7d566) so the next workflow run should remove it.

I also want to take the chance to clarify the format we use a bit. `References` and `GitHub` are both sub-sections of the `PoC` section. We just decided to separate them because they're handled by different processes in the workflow. `GitHub` covers GitHub repositories exclusively (not including gists), and `References` covers everything else. So your gist was actually included as a PoCs all along :)

Let me know if you have any questions and thank you so much for your continuous contributions!
