### ISSUE TITLE
Add CVE-2021-34785 and CVE-2021-34786 

### ISSUE THREAD

**Issue by eslam3kl** [trickest/cve#9]
Vulnerable product: Cisco BroadWorks 
Author: Eslam Akl (@eslam3kll)

CVE-2021–34785: IDOR lead to privileges escalation “Admin account takeover”
CVE-2021-34786: IDOR lead to delete arbitrary admin user accounts 

POC: https://eslam3kl.medium.com/cisco-broadworks-vulnerabilities-cve-2021-34785-cve-2021-34786-91ee2be5a200

**Comment by mhmdiaa** [comment]
Hi @eslam3kl,

Looks like the workflow has already picked up your repository :) 
- https://github.com/trickest/cve/blob/main/2021/CVE-2021-34785.md#github
- https://github.com/trickest/cve/blob/main/2021/CVE-2021-34786.md#github

Since this repository already includes a link to your writeup, it will work as a reference.
Thanks!
